Add Big Sur support

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -380,6 +380,7 @@ if [[ "$OSTYPE" =~ "darwin" ]]; then
     XCODE_CMD="xcode-select"
     XCODE_PATH=$($XCODE_CMD -p)
     DIRS+=("$XCODE_PATH/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include $XCODE_PATH/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib")
+    DIRS+=("$XCODE_PATH/SDKs/MacOSX.sdk/usr/include $XCODE_PATH/SDKs/MacOSX.sdk/usr/lib")
     DIRS+=("$XCODE_PATH/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include $XCODE_PATH/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib")
 elif [[ "$OSTYPE" =~ "msys" ]]; then
     SOLIBSUFFIX=dll
@@ -484,7 +485,13 @@ fi
 # zlib
 if ! find_library "zlib" "z" "zlib.h" "libz.a" "libz.$SOLIBSUFFIX*"; then
     if ! find_library "zlib" "z" "zlib.h" "zlib.a" "zlib.$SOLIBSUFFIX*"; then
-        error "zlib" "not found (please install zlib-devel package)"
+        if [[ "$OSTYPE" =~ "darwin" ]]; then
+            if ! find_library "zlib" "z" "zlib.h" "zlib.a" "libz.tbd"; then
+                error "zlib" "not found (please install zlib package)"
+            fi
+        else
+            error "zlib" "not found (please install zlib-devel package)"
+        fi
     fi
 fi
 
